config/routes.rb
Fna::Application.routes.draw do
  resources :relationships

  get "pages/welcome"

  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"

  resources :users

  root to: 'users#new'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  #validate email, username
  validates :email, uniqueness: true, presence: true, format: { with: /^[\w.+-]+@([\w]+.)+\w+$/ }
  validates :username, uniqueness: true, presence: true
  #validate password
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..40},
                       :on => :create
  validates :password, :confirmation => true,
                       :length => {:within => 6..40},
                       :allow_blank => false,
                       :on => :update
  attr_accessible :email, :password, :password_confirmation, :username, :gender

  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followed_relationships, class_name: "Relationship", foreign_key: "follower_id"

  has_many :followers, through: :follower_relationships
  has_many :followeds, through: :followed_relationships
  
  def following? user
    self.followeds.include? user
  end
  
  def follow user
    Relationship.create follower_id: self.id, followed_id: user.id
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
	def current_user
	  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
        @relationship = Relationship.new
        @relationship.followed_id = params[:followed_id]
        @relationship.follower_id = current_user.id
    if @relationship.save
        redirect_to User.find params[:followed_id]
    else
        flash[:error] = "Couldn't Follow"
        redirect_to root_url
    end
  end
  
  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    redirect_to user_path params[:id]
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        #redirect after login
        redirect_to pages_welcome_url, notice: "Logged in!"
    else
        flash[:error] = "Wrong Username or Password."
        redirect_to root_url
    end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_url, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		if current_user
			redirect_to pages_welcome_url
		else
			@user = User.new
		end
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			session[:user_id] = @user.id
			#redirect after login
			redirect_to pages_welcome_url, notice: "You're Lonely no more!"
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		
		@relationship = Relationship.where(
        follower_id: current_user.id,
        followed_id: @user.id
    ).first_or_initialize if current_user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>For-Never Alone Project</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-narrow">
		<div class="row-fluid">
			<div class="span12">
			<!-- login/logout form -->
				
				  	<% if current_user %>
				    <%= link_to "Log Out", sessions_destroy_path, :class => 'btn offset10' %>
					<% else %>
						<!-- Button to trigger modal -->
						<a href="#myModal" role="button" class="btn offset10" data-toggle="modal">Login</a>
						<!-- Modal -->
						<div id="myModal" class="modal hide fade span4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
							    <h3 id="myModalLabel">F.A no more...</h3>
							</div>
					    <%= form_tag sessions_create_path do %>
					        <%= text_field_tag :username, nil, placeholder: "username" %>
					        <%= password_field_tag :password, nil,  placeholder: "password" %>
					        <%= submit_tag "Log In", :class => 'btn' %>
				        <% end %>
				        </div>	
					<% end %>
				
			
			<!-- end login form -->
			<div class="containerTopbar">
				<div class="span6">
					<h1>For Never Alone</h1>
				</div>	
				<div class="span3">
					<h5>Alone or Not Alone...</h5>
				</div>
				<div class="span3">
					<img src="/img/logo.png" width=70>
				</div>
			</div>

			
				<%= yield %>
			
			</div>
		</div>
	</div>
	<!-- javascript -->
	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/welcome.html.erb
<h1>Pages#welcome</h1>
<p>Find me in app/views/pages/welcome.html.erb</p>

app/views/users/new.html.erb
<div class="span4 offset1 reg">
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= f.text_field :email, placeholder: "email" %>
    <%= f.text_field :username, placeholder: "username" %>
    <%= f.select :gender, %w{ Male Female }, placeholder: "Gender" %>
    <%= f.password_field :password, placeholder: "password" %>
    <%= f.password_field :password_confirmation, placeholder: "password" %>
    <%= f.submit "Create Account", :class => 'btn' %>
  <% end %>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%= @user.username %> |
<%= @user.email %> |
<%= @user.gender %> |
<%= @user.followers.count %> |
<%= @user.followeds.count %>
<br />
<% if current_user and @user != current_user %>
    <% if current_user.following? @user %>
        <%= form_tag relationship_path, method: :delete do %>
            <%= submit_tag "Unfollow" %>
        <% end %>
    <% else %>
        <%= form_for @relationship do %>
            <%= hidden_field_tag :followed_id, @user.id %>
            <%= submit_tag "Follow" %>
        <% end %>
    <% end %>
<% end %>